
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE LPAREN MINUS NUMBER PLUS PRINT RPAREN STRING TIMESstatement : PRINT expressionexpression : expression PLUS termexpression : expression MINUS termexpression : termterm : term TIMES factorterm : term DIVIDE factorterm : factorfactor : NUMBERfactor : STRINGfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'PRINT':([0,],[2,]),'$end':([1,3,4,5,6,7,14,15,16,17,18,],[0,-1,-4,-7,-8,-9,-2,-3,-5,-6,-10,]),'NUMBER':([2,8,9,10,11,12,],[6,6,6,6,6,6,]),'STRING':([2,8,9,10,11,12,],[7,7,7,7,7,7,]),'LPAREN':([2,8,9,10,11,12,],[8,8,8,8,8,8,]),'PLUS':([3,4,5,6,7,13,14,15,16,17,18,],[9,-4,-7,-8,-9,9,-2,-3,-5,-6,-10,]),'MINUS':([3,4,5,6,7,13,14,15,16,17,18,],[10,-4,-7,-8,-9,10,-2,-3,-5,-6,-10,]),'RPAREN':([4,5,6,7,13,14,15,16,17,18,],[-4,-7,-8,-9,18,-2,-3,-5,-6,-10,]),'TIMES':([4,5,6,7,14,15,16,17,18,],[11,-7,-8,-9,11,11,-5,-6,-10,]),'DIVIDE':([4,5,6,7,14,15,16,17,18,],[12,-7,-8,-9,12,12,-5,-6,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([2,8,],[3,13,]),'term':([2,8,9,10,],[4,4,14,15,]),'factor':([2,8,9,10,11,12,],[5,5,5,5,16,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> PRINT expression','statement',2,'p_statement_print','sintatico.py',9),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','sintatico.py',15),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','sintatico.py',19),
  ('expression -> term','expression',1,'p_expression_term','sintatico.py',23),
  ('term -> term TIMES factor','term',3,'p_term_times','sintatico.py',27),
  ('term -> term DIVIDE factor','term',3,'p_term_divide','sintatico.py',31),
  ('term -> factor','term',1,'p_term_factor','sintatico.py',35),
  ('factor -> NUMBER','factor',1,'p_factor_number','sintatico.py',39),
  ('factor -> STRING','factor',1,'p_factor_string','sintatico.py',43),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_group','sintatico.py',47),
]
